### ISSUE TITLE
Better to include the content of k.h in this repo instead of downloading during compilation

### ISSUE THREAD

**Issue by lwshang** [zholos/qml#8]
As mentioned in README of [KxSysrems/kdb](https://github.com/KxSystems/kdb/blob/master/README.TXT) :

> - This is not a high-availability hosting service
> - Updates to the repo may break your application 
> - Code refactoring might return 404s to your application

Therefore, I believe it's better to include the content of k.h in this repo instead of downloading during compilation.

Right now (2017.07.25), when I try to compile qml. It fails because the content of iniclude/k.h is "404  not found".

**Comment by zholos** [comment]
Looks like [KxSystems/code.archive](https://github.com/KxSystems/code.archive) was renamed to [KxSystems/kdb](https://github.com/KxSystems/kdb).

I updated the URL for k.h to the new repo and made it point to a specific commit rather than the latest version so it's more stable.

I don't want to include any external code in the qml repo. There are a few other downloads and any one of them can change hosting or be down temporarily - can't include them all.
